<a href="https://colab.research.google.com/github/Jaya9522/almabetter_assignments/blob/main/Assignment_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [2]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [3]:
# Your code here
random_integers[:5,2:4].mean()

286058.5

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [4]:
# Create the 10 points
points=np.random.randint(5,20,size=(10,2))
points

array([[19, 12],
       [10, 16],
       [ 7, 12],
       [10, 19],
       [ 5,  9],
       [ 7,  7],
       [ 5, 14],
       [16,  6],
       [ 5,  8],
       [ 6,  8]])

In [5]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
def eucledian_distance(point1,point2):
    """Calculates and returns Eucledian Distance"""
    x1,y1=point1
    x2,y2=point2
    return round(((x2-x1)**2+(y2-y1)**2)**0.5,2)                                # calculating eucledian distance 
    
euclidean_distances=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(eucledian_distance(points[i],points[j]))
    euclidean_distances.append(np.asarray(inner_llist))
euclidean_distances = np.asarray(euclidean_distances)
print(euclidean_distances)




[[ 0.    9.85 12.   11.4  14.32 13.   14.14  6.71 14.56 13.6 ]
 [ 9.85  0.    5.    3.    8.6   9.49  5.39 11.66  9.43  8.94]
 [12.    5.    0.    7.62  3.61  5.    2.83 10.82  4.47  4.12]
 [11.4   3.    7.62  0.   11.18 12.37  7.07 14.32 12.08 11.7 ]
 [14.32  8.6   3.61 11.18  0.    2.83  5.   11.4   1.    1.41]
 [13.    9.49  5.   12.37  2.83  0.    7.28  9.06  2.24  1.41]
 [14.14  5.39  2.83  7.07  5.    7.28  0.   13.6   6.    6.08]
 [ 6.71 11.66 10.82 14.32 11.4   9.06 13.6   0.   11.18 10.2 ]
 [14.56  9.43  4.47 12.08  1.    2.24  6.   11.18  0.    1.  ]
 [13.6   8.94  4.12 11.7   1.41  1.41  6.08 10.2   1.    0.  ]]


In [6]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
def manhattan_distance(point1,point2):
    """Calclates and returns Manhattan Distance"""
    x1,y1=point1
    x2,y2=point2
    return round((abs(x2-x1)+abs(y2-y1)),2)                                     # The manhattan distance            

manhattan_distances=[]
for i in range(10):
    inner_llist=[]
    for j in range(10):
        inner_llist.append(manhattan_distance(points[i],points[j]))             
    manhattan_distances.append(np.asarray(inner_llist))
manhattan_distances=np.asarray(manhattan_distances)
print(manhattan_distances)




[[ 0 13 12 16 17 17 16  9 18 17]
 [13  0  7  3 12 12  7 16 13 12]
 [12  7  0 10  5  5  4 15  6  5]
 [16  3 10  0 15 15 10 19 16 15]
 [17 12  5 15  0  4  5 14  1  2]
 [17 12  5 15  4  0  9 10  3  2]
 [16  7  4 10  5  9  0 19  6  7]
 [ 9 16 15 19 14 10 19  0 13 12]
 [18 13  6 16  1  3  6 13  0  1]
 [17 12  5 15  2  2  7 12  1  0]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [8]:
# Your code here
nearest_points_manhattan=[]
for ind,arr in enumerate(manhattan_distances+np.identity(10)*1000):
    nearest_points_manhattan.append((points[ind],points[arr.argmin()]))         # index of the value with min distance is stored and the corrosponding points accesed
    
print(nearest_points_manhattan)

nearest_points_euclidean=[]
for ind,arr in enumerate(euclidean_distances+np.identity(10)*1000):
    nearest_points_euclidean.append((points[ind],points[arr.argmin()]))         # index of the value with min distance is stored and the corrosponding points accesed

print(nearest_points_euclidean)




[(array([19, 12]), array([16,  6])), (array([10, 16]), array([10, 19])), (array([ 7, 12]), array([ 5, 14])), (array([10, 19]), array([10, 16])), (array([5, 9]), array([5, 8])), (array([7, 7]), array([6, 8])), (array([ 5, 14]), array([ 7, 12])), (array([16,  6]), array([19, 12])), (array([5, 8]), array([5, 9])), (array([6, 8]), array([5, 8]))]
[(array([19, 12]), array([16,  6])), (array([10, 16]), array([10, 19])), (array([ 7, 12]), array([ 5, 14])), (array([10, 19]), array([10, 16])), (array([5, 9]), array([5, 8])), (array([7, 7]), array([6, 8])), (array([ 5, 14]), array([ 7, 12])), (array([16,  6]), array([19, 12])), (array([5, 8]), array([5, 9])), (array([6, 8]), array([5, 8]))]


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [10]:
# Your code below ..
contiguous_list=[]
big_matrix=np.random.randint(1,100,size=(10,10))
print(big_matrix)
for row in range(0,8):      # for accessing rows one by one
    for col in range(0,8):  # for accessing rows one by one
        contiguous_list.append(big_matrix[row:row+3,col:col+3])

contiguous_array=np.asarray(contiguous_list)

print(contiguous_array)


[[70 44 66 91 86 81 14 80 43 24]
 [ 3 80 76 29 50 84 83 88 91 81]
 [79  8 98 46 11 32 23 65 18  2]
 [70 55 87 22 75 12 16 78 84 40]
 [74 33 19 68 68 74 63 26 55 57]
 [47 27 67  2 89 76 86 31 76 55]
 [39 34 99 76  6  2 57 72 99 78]
 [21 78 93  4 57 41 65 80 38 55]
 [61  4 29 74 48 18 45 71  2 50]
 [31 39 84 47 87 98 50 23 77 88]]
[[[70 44 66]
  [ 3 80 76]
  [79  8 98]]

 [[44 66 91]
  [80 76 29]
  [ 8 98 46]]

 [[66 91 86]
  [76 29 50]
  [98 46 11]]

 [[91 86 81]
  [29 50 84]
  [46 11 32]]

 [[86 81 14]
  [50 84 83]
  [11 32 23]]

 [[81 14 80]
  [84 83 88]
  [32 23 65]]

 [[14 80 43]
  [83 88 91]
  [23 65 18]]

 [[80 43 24]
  [88 91 81]
  [65 18  2]]

 [[ 3 80 76]
  [79  8 98]
  [70 55 87]]

 [[80 76 29]
  [ 8 98 46]
  [55 87 22]]

 [[76 29 50]
  [98 46 11]
  [87 22 75]]

 [[29 50 84]
  [46 11 32]
  [22 75 12]]

 [[50 84 83]
  [11 32 23]
  [75 12 16]]

 [[84 83 88]
  [32 23 65]
  [12 16 78]]

 [[83 88 91]
  [23 65 18]
  [16 78 84]]

 [[88 91 81]
  [65 18  2]
  [78 84 40]]

 [[79  8 98]


#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [11]:
# Your function below
def get_nearest_value(elem,array):
    """Return the nearest value in the given array for given input"""
    nearest_value = array.flat[np.abs(array - elem).argmin()]                   # flatern and then findind the value with min difrence for given input
    return nearest_value
array=np.random.randint(10,500, size=(1, 15))
print(array)





[[368  63 465 310  28  70 195 295 105 499 420  31 246 324 249]]


In [12]:
ele=int(input("Enter the element for which you want to find the nearest value for "))
print(f"Nearest point to {ele} is {get_nearest_value(ele,array)}")

Enter the element for which you want to find the nearest value for 12
Nearest point to 12 is 28
