<a href="https://colab.research.google.com/github/Jaya9522/almabetter_assignments/blob/main/Assignment_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [2]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [4]:
# Your code here
array=print(random_integers[:5, 2:4])




[[202553 140037]
 [261540 481981]
 [110795 394863]
 [408830 485118]
 [265455 109413]]


In [7]:
np.mean(random_integers[:5, 2:4])

286058.5

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points


In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair





In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.





## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here





# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [9]:
# Your code below ..
import numpy as np
arra1 = np.random.randint(0,11,(10,10))
print("Original arrays:")
print(arra1)
n = 3
i = 1 + (arra1.shape[0]-3)
j = 1 + (arra1.shape[1]-3)
result = np.lib.stride_tricks.as_strided(arra1, shape=(i, j, n, n), strides = arra1.strides + arra1.strides)
print("\nContiguous 4x4 blocks:")
print(result)










Original arrays:
[[ 5  3 10  7  7  5  3  2  2 10]
 [ 0  9  2  2  6  6  3 10  5  1]
 [ 5  6 10 10  1  4  3  6  5  3]
 [ 3  2  7  0 10  5  4  1 10  5]
 [ 0 10  7  2  8  1  3  2  7  2]
 [10  0  5  7  1  9 10  7  4  6]
 [ 0  1  1  5  6  6  5 10  9  3]
 [ 3  5  7  9  9  0  2  3  3  9]
 [ 9  6  8  5 10  2  1  8  5  6]
 [ 6  8  6  1  2  5  1  8  7  2]]

Contiguous 4x4 blocks:
[[[[ 5  3 10]
   [ 0  9  2]
   [ 5  6 10]]

  [[ 3 10  7]
   [ 9  2  2]
   [ 6 10 10]]

  [[10  7  7]
   [ 2  2  6]
   [10 10  1]]

  [[ 7  7  5]
   [ 2  6  6]
   [10  1  4]]

  [[ 7  5  3]
   [ 6  6  3]
   [ 1  4  3]]

  [[ 5  3  2]
   [ 6  3 10]
   [ 4  3  6]]

  [[ 3  2  2]
   [ 3 10  5]
   [ 3  6  5]]

  [[ 2  2 10]
   [10  5  1]
   [ 6  5  3]]]


 [[[ 0  9  2]
   [ 5  6 10]
   [ 3  2  7]]

  [[ 9  2  2]
   [ 6 10 10]
   [ 2  7  0]]

  [[ 2  2  6]
   [10 10  1]
   [ 7  0 10]]

  [[ 2  6  6]
   [10  1  4]
   [ 0 10  5]]

  [[ 6  6  3]
   [ 1  4  3]
   [10  5  4]]

  [[ 6  3 10]
   [ 4  3  6]
   [ 5  4  1]]

  [[ 3 10 

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [11]:


import numpy as np
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.random.random(500)
print(array)


[0.4875319  0.89693823 0.32091241 0.26392889 0.94354031 0.84410571
 0.80462925 0.14520946 0.94633145 0.84085134 0.48450639 0.70121936
 0.10670261 0.36806935 0.96179063 0.74024963 0.19388827 0.23536582
 0.60623426 0.11434587 0.04221996 0.19193255 0.10343326 0.25953345
 0.84760668 0.7795603  0.76488614 0.21899707 0.12414673 0.9791183
 0.19905389 0.64113812 0.51934758 0.84976248 0.91396676 0.61363658
 0.98938188 0.1210843  0.89406868 0.86274342 0.23237793 0.29630802
 0.34687632 0.001889   0.72921641 0.2443015  0.93553206 0.43477497
 0.51498694 0.0895478  0.33555967 0.19160402 0.73259914 0.50794252
 0.37270837 0.85574085 0.49154033 0.38088864 0.25007842 0.74224749
 0.33456836 0.97082531 0.07077944 0.39151745 0.62595693 0.57757217
 0.88952415 0.93643371 0.75185673 0.56788475 0.35999463 0.65960514
 0.6893385  0.41782029 0.90570102 0.38695125 0.4172195  0.9151791
 0.02603225 0.59282841 0.75346806 0.44325584 0.53644714 0.42123128
 0.21229574 0.77958652 0.02455713 0.51519744 0.54463426 0.906280

In [12]:
value= 50

In [13]:
print(find_nearest(array, value))

0.9998448398228111
